update tool set description = 'Crie sua própria loja online de forma rápida e simples', file_id = 476 where cod_name like 'SHOP';
update tool set description = 'Deixe disponíveis seus horários de funcionamento e avisos de datas comemorativas.', file_id = 475 where cod_name like 'BUSINESSHOUR';
update tool set description = 'Deixe disponíveis seus contatos: fone, e-mail, whatsapp e mais.', file_id = 472 where cod_name like 'CONTACT';
update tool set description = 'Crie um canal de comunicação com seus seguidores adicionando o formulário Fale Conosco', file_id = 468 where cod_name like 'CONTACTUS';
update tool set description = 'Cria uma área de FAQ no seu Ido para que seus seguidores consigam tirar dúvidas.', file_id = 473 where cod_name like 'FAQ';
update tool set description = 'Crie banners de destaque, como anúncio, promoções, produtos, etc.', file_id = 470 where cod_name like 'IMAGEBANNER';
update tool set description = 'Cria uma galeria de imagens e direcione para whatsapp, e-mail ou outro link externo', file_id = 469 where cod_name like 'IMAGECAROUSEL';
update tool set description = 'Crie um grupo de links e compartilhe com seus seguidores', file_id = 471 where cod_name like 'LINK';
update tool set description = 'Adicione um formulário de inscrição para envio de newsletters e captação de leads.', file_id = 474 where cod_name like 'NEWSLETTER';
update tool set description = 'Adicione conteúdos em PDF e disponibilize a seus clientes, possibilitando a captação de leads.', file_id = 478 where cod_name like 'PDF';
update tool set description = 'Disponibilize seus vídeos do youtube ou Vimeo no Ido', file_id = 477 where cod_name like 'VIDEOBANNER';
update tool set description = 'Adicione animações nos botões e cards de seu Ido', file_id = 471 where cod_name like 'BUTTONANIMATION';
