ALTER TABLE tool ADD COLUMN info_html varchar(50);

UPDATE tool SET name = 'api.model.tools.pdf', description = 'api.model.tools.pdfinfo'  where id = 9;
UPDATE tool SET name = 'api.model.tools.link', description = 'api.model.tools.linkinfo', info_html='api.model.tools.linkfaq' where id = 7;
UPDATE tool SET name = 'api.model.tools.contactus', description = 'api.model.tools.contactusinfo', info_html='api.model.tools.contactusfaq' where id = 3;
UPDATE tool SET name = 'api.model.tools.contact', description = 'api.model.tools.contactinfo', info_html='api.model.tools.contactfaq' where id = 2;
UPDATE tool SET name = 'api.model.tools.businesshour', description = 'api.model.tools.businesshourinfo', info_html='api.model.tools.businesshourfaq' where id = 1;
UPDATE tool SET name = 'api.model.tools.video', description = 'api.model.tools.videoinfo', info_html='api.model.tools.videofaq' where id = 10;
UPDATE tool SET name = 'api.model.tools.bannercarrossel', description = 'api.model.tools.bannercarrosselinfo', info_html='api.model.tools.bannercarrosselfaq' where id = 6;
UPDATE tool SET name = 'api.model.tools.store', description = 'api.model.tools.storeinfo', info_html='api.model.tools.storefaq' where id = 12;
UPDATE tool SET name = 'api.model.tools.bannerimage', description = 'api.model.tools.bannerimageinfo', info_html='api.model.tools.bannerimagefaq' where id = 5;
UPDATE tool SET name = 'api.model.tools.formnewsletter', description = 'api.model.tools.formnewsletterinfo', info_html='api.model.tools.formnewsletterfaq' where id = 8;
UPDATE tool SET name = 'api.model.tools.faq', description = 'api.model.tools.faqinfo', info_html='api.model.tools.faqfaq' where id = 4;
UPDATE tool SET name = 'api.model.tools.embedhtml', description = 'api.model.tools.embedhtmlinfo', info_html='api.model.tools.embedhtmlfaq' where id = 13;
UPDATE tool SET name = 'api.model.tools.logoebio', description = 'api.model.tools.logoebioinfo', info_html='api.model.tools.logoebiofaq' where id = 14;
UPDATE tool SET name = 'api.model.tools.menufooter', description = 'api.model.tools.menufooterinfo', info_html='api.model.tools.menufooterfaq' where id = 15;

alter table country add column coins varchar(5);
alter table country add column coins_name varchar(10);

update country set country = 'api.model.country.brasil', ddi = '55', coins = 'R$',coins_name = 'BRL' where id = 1; 
update country set country ='api.model.country.canada',ddi='1',coins='$',coins_name='CAD' where id =2;
update country set country ='api.model.country.estadosunidos',ddi='1',coins='$',coins_name='USD' where id =3;
update country set country ='api.model.country.afeganistao',ddi='93',coins='؋',coins_name='AFN' where id =4;
update country set country ='api.model.country.africadosul',ddi='27',coins='R',coins_name='ZAR' where id =5;
update country set country ='api.model.country.albania',ddi='355',coins='L',coins_name='ALL' where id =6;
update country set country ='api.model.country.alemanha',ddi='49',coins='€',coins_name='EUR' where id =7;
update country set country ='api.model.country.andorra',ddi='376',coins='€',coins_name='EUR' where id =8;
update country set country ='api.model.country.angola',ddi='244',coins='Kz',coins_name='AOA' where id =9;
update country set country ='api.model.country.anguila',ddi='1',coins='$',coins_name='XCD' where id =10;
update country set country ='api.model.country.antiguaebarbuda',ddi='1',coins='$',coins_name='XCD' where id =11;
update country set country ='api.model.country.antilhasneerlandesas',ddi='599',coins='$',coins_name='ANG' where id =12;
update country set country ='api.model.country.arabiasaudita',ddi='966',coins='ر.س',coins_name='SAR' where id =13;
update country set country ='api.model.country.argelia',ddi='213',coins='د.ج',coins_name='DZD' where id =14;
update country set country ='api.model.country.argentina',ddi='54',coins='$',coins_name='ARS' where id =15;
update country set country ='api.model.country.armenia',ddi='374',coins='€',coins_name='AMD' where id =16;
update country set country ='api.model.country.aruba',ddi='297',coins='ƒ',coins_name='AWG' where id =17;
update country set country ='api.model.country.ascensao',ddi='247',coins='$',coins_name='USD' where id =18;
update country set country ='api.model.country.australia',ddi='61',coins='$',coins_name='AUD' where id =19;
update country set country ='api.model.country.austria',ddi='43',coins='€',coins_name='EUR' where id =20;
update country set country ='api.model.country.azerbaijao',ddi='994',coins='₼',coins_name='AZN' where id =21;
update country set country ='api.model.country.bahamas',ddi='1',coins='$',coins_name='BSD' where id =22;
update country set country ='api.model.country.bangladexe',ddi='880',coins='৳',coins_name='BDT' where id =23;
update country set country ='api.model.country.barbados',ddi='1',coins='$',coins_name='BBD' where id =24;
update country set country ='api.model.country.barem',ddi='973',coins='.د.ب',coins_name='BHD' where id =25;
update country set country ='api.model.country.belgica',ddi='32',coins='€',coins_name='EUR' where id =26;
update country set country ='api.model.country.belize',ddi='501',coins='$',coins_name='BZD' where id =27;
update country set country ='api.model.country.benim',ddi='229',coins='Fr',coins_name='XOF' where id =28;
update country set country ='api.model.country.bermudas',ddi='1',coins='$',coins_name='BMD' where id =29;
update country set country ='api.model.country.bielorrussia',ddi='375',coins='Br',coins_name='BYR' where id =30;
update country set country ='api.model.country.bolivia',ddi='591',coins='Bs.',coins_name='BOB' where id =31;
update country set country ='api.model.country.bosniaeherzegovina',ddi='387',coins='km',coins_name='BAM' where id =32;
update country set country ='api.model.country.botsuana',ddi='267',coins='P',coins_name='BWP' where id =33;
update country set country ='api.model.country.brunei',ddi='673',coins='$',coins_name='BDN' where id =34;
update country set country ='api.model.country.bulgaria',ddi='359',coins='лв',coins_name='BGN' where id =35;
update country set country ='api.model.country.burquinafasso',ddi='226',coins='Fr',coins_name='XOF' where id =36;
update country set country ='api.model.country.burundi',ddi='257',coins='Fr',coins_name='BIF' where id =37;
update country set country ='api.model.country.butao',ddi='975',coins='Nu.',coins_name='BTN' where id =38;
update country set country ='api.model.country.caboverde',ddi='238',coins='$',coins_name='CVE' where id =39;
update country set country ='api.model.country.camaroes',ddi='237',coins='Fr',coins_name='XAF' where id =40;
update country set country ='api.model.country.camboja',ddi='855',coins='៛',coins_name='KHR' where id =41;
update country set country ='api.model.country.catar',ddi='974',coins='ر.ق',coins_name='QAR' where id =42;
update country set country ='api.model.country.cazaquistao',ddi='7',coins='₸',coins_name='KZT' where id =43;
update country set country ='api.model.country.chade',ddi='235',coins='Fr',coins_name='XAF' where id =44;
update country set country ='api.model.country.chile',ddi='56',coins='$',coins_name='CLP' where id =45;
update country set country ='api.model.country.china',ddi='86',coins='¥',coins_name='CNY' where id =46;
update country set country ='api.model.country.chipre',ddi='357',coins='€',coins_name='EUR' where id =47;
update country set country ='api.model.country.colombia',ddi='57',coins='$',coins_name='COP' where id =48;
update country set country ='api.model.country.comores',ddi='269',coins='Fr',coins_name='KMF' where id =49;
update country set country ='api.model.country.congo-brazavile',ddi='242',coins='Fr',coins_name='CDF' where id =50;
update country set country ='api.model.country.congo-quinxassa',ddi='243',coins='Fr',coins_name='XAF' where id =51;
update country set country ='api.model.country.coreiadonorte',ddi='850',coins='₩',coins_name='KPW' where id =52;
update country set country ='api.model.country.coreiadosul',ddi='82',coins='₩',coins_name='KRW' where id =53;
update country set country ='api.model.country.costadomarfim',ddi='225',coins='Fr',coins_name='XOF' where id =54;
update country set country ='api.model.country.costarica',ddi='506',coins='₡',coins_name='CRC' where id =55;
update country set country ='api.model.country.croacia',ddi='385',coins='kn',coins_name='HRK' where id =56;
update country set country ='api.model.country.cuba',ddi='53',coins='$',coins_name='CUC' where id =57;
update country set country ='api.model.country.dinamarca',ddi='45',coins='kr',coins_name='DKK' where id =58;
update country set country ='api.model.country.djibuti',ddi='253',coins='$',coins_name='CAD' where id =59;
update country set country ='api.model.country.dominica',ddi='1',coins='$',coins_name='XCD' where id =60;
update country set country ='api.model.country.egipto',ddi='20',coins='£',coins_name='EGP' where id =61;
update country set country ='api.model.country.elsalvador',ddi='503',coins='$',coins_name='USD' where id =62;
update country set country ='api.model.country.emiradosarabesunidos',ddi='971',coins='د.إ',coins_name='AED' where id =63;
update country set country ='api.model.country.equador',ddi='593',coins='$',coins_name='USD' where id =64;
update country set country ='api.model.country.eritreia',ddi='291',coins='Nfk',coins_name='ERN' where id =65;
update country set country ='api.model.country.eslovaquia',ddi='421',coins='€',coins_name='EUR' where id =66;
update country set country ='api.model.country.eslovenia',ddi='386',coins='€',coins_name='EUR' where id =67;
update country set country ='api.model.country.espanha',ddi='34',coins='€',coins_name='EUR' where id =68;
update country set country ='api.model.country.essuatini',ddi='268',coins='€',coins_name='EUR' where id =69;
update country set country ='api.model.country.estonia',ddi='691',coins='€',coins_name='EUR' where id =146;
update country set country ='api.model.country.etiopia',ddi='372',coins='€',coins_name='EUR' where id =70;
update country set country ='api.model.country.fiji',ddi='251',coins='Br',coins_name='ETB' where id =71;
update country set country ='api.model.country.filipinas',ddi='679',coins='kr',coins_name='DKK' where id =72;
update country set country ='api.model.country.finlandia',ddi='63',coins='$',coins_name='FJD' where id =73;
update country set country ='api.model.country.franca',ddi='358',coins='₱',coins_name='PHP' where id =74;
update country set country ='api.model.country.gabao',ddi='33',coins='€',coins_name='EUR' where id =75;
update country set country ='api.model.country.gambia',ddi='241',coins='Fr',coins_name='XAF' where id =76;
update country set country ='api.model.country.gana',ddi='220',coins='D',coins_name='GMD' where id =77;
update country set country ='api.model.country.georgia',ddi='233',coins='₵',coins_name='GHS' where id =78;
update country set country ='api.model.country.gibraltar',ddi='995',coins='ლ',coins_name='GEL' where id =79;
update country set country ='api.model.country.granada',ddi='350',coins='£',coins_name='GIP' where id =80;
update country set country ='api.model.country.grecia',ddi='1',coins='$',coins_name='XCD' where id =81;
update country set country ='api.model.country.groenlandia',ddi='30',coins='€',coins_name='EUR' where id =82;
update country set country ='api.model.country.guadalupe',ddi='299',coins='Kr.',coins_name='DKK' where id =83;
update country set country ='api.model.country.guam',ddi='590',coins='€',coins_name='EUR' where id =84;
update country set country ='api.model.country.guatemala',ddi='1',coins='$',coins_name='USD' where id =85;
update country set country ='api.model.country.guiana',ddi='502',coins='Q',coins_name='GTQ' where id =86;
update country set country ='api.model.country.guianafrancesa',ddi='592',coins='$',coins_name='GYD' where id =87;
update country set country ='api.model.country.guine',ddi='594',coins='$',coins_name='GYD' where id =88;
update country set country ='api.model.country.guine-bissau',ddi='224',coins='Fr',coins_name='GNF' where id =89;
update country set country ='api.model.country.guineequatorial',ddi='240',coins='Fr',coins_name='XOF' where id =91;
update country set country ='api.model.country.haiti',ddi='245',coins='Fr',coins_name='GNF' where id =90;
update country set country ='api.model.country.honduras',ddi='509',coins='G',coins_name='HTG' where id =92;
update country set country ='api.model.country.hongkong',ddi='504',coins='L',coins_name='HNL' where id =93;
update country set country ='api.model.country.hungria',ddi='852',coins='$',coins_name='HKD' where id =94;
update country set country ='api.model.country.iemen',ddi='36',coins='Ft',coins_name='HUF' where id =95;
update country set country ='api.model.country.ilhascaima',ddi='967',coins='﷼',coins_name='YER' where id =96;
update country set country ='api.model.country.ilhachristmas',ddi='672',coins='$',coins_name='USD' where id =98;
update country set country ='api.model.country.ilhascocos',ddi='672',coins='$',coins_name='USD' where id =102;
update country set country ='api.model.country.ilhascook',ddi='672',coins='$',coins_name='USD' where id =107;
update country set country ='api.model.country.ilhasferoe',ddi='1',coins='$',coins_name='USD' where id =97;
update country set country ='api.model.country.ilhaheardeilhasmcdonald',ddi='672',coins='$',coins_name='USD' where id =99;
update country set country ='api.model.country.maldivas',ddi='682',coins='$',coins_name='USD' where id =100;
update country set country ='api.model.country.ilhasmalvinas',ddi='298',coins='$',coins_name='USD' where id =101;
update country set country ='api.model.country.ilhasmarianasdonorte',ddi='500',coins='$',coins_name='USD' where id =104;
update country set country ='api.model.country.ilhasmarshall',ddi='1',coins='$',coins_name='USD' where id =105;
update country set country ='api.model.country.ilhanorfolque',ddi='692',coins='$',coins_name='USD' where id =106;
update country set country ='api.model.country.ilhassalomao',ddi='677',coins='$',coins_name='USD' where id =108;
update country set country ='api.model.country.ilhasvirgensamericanas',ddi='1',coins='$',coins_name='USD' where id =109;
update country set country ='api.model.country.ilhasvirgensbritanicas',ddi='1',coins='$',coins_name='USD' where id =110;
update country set country ='api.model.country.india',ddi='91',coins='',coins_name='INR' where id =111;
update country set country ='api.model.country.indonesia',ddi='62',coins='Rp',coins_name='IDR' where id =112;
update country set country ='api.model.country.ira',ddi='98',coins='﷼',coins_name='IRR' where id =113;
update country set country ='api.model.country.iraque',ddi='964',coins='ع.د',coins_name='IQD' where id =114;
update country set country ='api.model.country.irlanda',ddi='353',coins='€',coins_name='EUR' where id =115;
update country set country ='api.model.country.islandia',ddi='354',coins='kr',coins_name='ISK' where id =116;
update country set country ='api.model.country.israel',ddi='972',coins='₪',coins_name='ILS' where id =117;
update country set country ='api.model.country.italia',ddi='39',coins='€',coins_name='EUR' where id =118;
update country set country ='api.model.country.jamaica',ddi='1',coins='$',coins_name='JMD' where id =119;
update country set country ='api.model.country.japao',ddi='81',coins='¥',coins_name='JPY' where id =120;
update country set country ='api.model.country.jordania',ddi='962',coins='د.ا',coins_name='JOD' where id =121;
update country set country ='api.model.country.kosovo',ddi='383',coins='€',coins_name='EUR' where id =122;
update country set country ='api.model.country.kuwait',ddi='965',coins='€',coins_name='EUR' where id =123;
update country set country ='api.model.country.laos',ddi='856',coins='₭',coins_name='LAK' where id =124;
update country set country ='api.model.country.lesoto',ddi='266',coins='R',coins_name='ZAR' where id =125;
update country set country ='api.model.country.letonia',ddi='371',coins='€',coins_name='EUR' where id =126;
update country set country ='api.model.country.libano',ddi='961',coins='ل.ل',coins_name='LBP' where id =127;
update country set country ='api.model.country.liberia',ddi='231',coins='$',coins_name='LRD' where id =128;
update country set country ='api.model.country.libia',ddi='218',coins='ل.د',coins_name='LYD' where id =129;
update country set country ='api.model.country.liechtenstein',ddi='423',coins='Fr',coins_name='CHF' where id =130;
update country set country ='api.model.country.lituania',ddi='370',coins='€',coins_name='EUR' where id =131;
update country set country ='api.model.country.luxemburgo',ddi='352',coins='€',coins_name='EUR' where id =132;
update country set country ='api.model.country.macau',ddi='853',coins='P',coins_name='MOP' where id =133;
update country set country ='api.model.country.macedoniadonorte',ddi='389',coins='ден',coins_name='MKD' where id =134;
update country set country ='api.model.country.madagascar',ddi='261',coins='Ar',coins_name='MGA' where id =135;
update country set country ='api.model.country.malasia',ddi='269',coins='€',coins_name='EUR' where id =144;
update country set country ='api.model.country.malaui',ddi='60',coins='RM',coins_name='MYR' where id =136;
update country set country ='api.model.country.mali',ddi='265',coins='MK',coins_name='MWK' where id =137;
update country set country ='api.model.country.malta',ddi='960',coins='.ރ',coins_name='MVR' where id =103;
update country set country ='api.model.country.marrocos',ddi='223',coins='Fr',coins_name='XOF' where id =138;
update country set country ='api.model.country.martinica',ddi='356',coins='€',coins_name='EUR' where id =139;
update country set country ='api.model.country.mauricia',ddi='212',coins='د.م.',coins_name='MAD' where id =140;
update country set country ='api.model.country.mauritania',ddi='596',coins='€',coins_name='EUR' where id =141;
update country set country ='api.model.country.maiote',ddi='230',coins='₨',coins_name='MUR' where id =142;
update country set country ='api.model.country.mexico',ddi='222',coins='UM',coins_name='MRO' where id =143;
update country set country ='api.model.country.estadosfederadosdamicronesia',ddi='52',coins='$',coins_name='MXN' where id =145;
update country set country ='api.model.country.mocambique',ddi='95',coins='Ks',coins_name='MMK' where id =153;
update country set country ='api.model.country.moldavia',ddi='258',coins='MT',coins_name='MZN' where id =147;
update country set country ='api.model.country.monaco',ddi='373',coins='L',coins_name='MDL' where id =148;
update country set country ='api.model.country.mongolia',ddi='377',coins='€',coins_name='EUR' where id =149;
update country set country ='api.model.country.montenegro',ddi='976',coins='₮',coins_name='MNT' where id =150;
update country set country ='api.model.country.monserrate',ddi='1',coins='$',coins_name='XCD' where id =152;
update country set country ='api.model.country.mianmar',ddi='382',coins='€',coins_name='EUR' where id =151;
update country set country ='api.model.country.namibia',ddi='264',coins='$',coins_name='NAD' where id =154;
update country set country ='api.model.country.nauru',ddi='674',coins='$',coins_name='AUD' where id =155;
update country set country ='api.model.country.nepal',ddi='977',coins='₨',coins_name='NPR' where id =156;
update country set country ='api.model.country.nicaragua',ddi='505',coins='C$',coins_name='NIO' where id =157;
update country set country ='api.model.country.niger',ddi='227',coins='Fr',coins_name='XOF' where id =158;
update country set country ='api.model.country.nigeria',ddi='234',coins='₦',coins_name='NGN' where id =159;
update country set country ='api.model.country.niue',ddi='683',coins='$',coins_name='NZD' where id =160;
update country set country ='api.model.country.noruega',ddi='47',coins='kr',coins_name='NOK' where id =161;
update country set country ='api.model.country.novacaledonia',ddi='687',coins='Fr',coins_name='XPF' where id =162;
update country set country ='api.model.country.novazelandia',ddi='64',coins='$',coins_name='NZD' where id =163;
update country set country ='api.model.country.oma',ddi='968',coins='ر.ع.',coins_name='OMR' where id =164;
update country set country ='api.model.country.paisesbaixos',ddi='31',coins='€',coins_name='EUR' where id =165;
update country set country ='api.model.country.palau',ddi='680',coins='$',coins_name='USD' where id =166;
update country set country ='api.model.country.palestina',ddi='970',coins='د.ا',coins_name='JOD' where id =167;
update country set country ='api.model.country.panama',ddi='507',coins='$',coins_name='USD' where id =168;
update country set country ='api.model.country.papua-novaguine',ddi='675',coins='K',coins_name='PGK' where id =169;
update country set country ='api.model.country.paquistao',ddi='92',coins='₨',coins_name='PKR' where id =170;
update country set country ='api.model.country.paraguai',ddi='595',coins='₲',coins_name='PYG' where id =171;
update country set country ='api.model.country.peru',ddi='51',coins='S/.',coins_name='PEN' where id =172;
update country set country ='api.model.country.polinesiafrancesa',ddi='689',coins='Fr',coins_name='XPF' where id =173;
update country set country ='api.model.country.polonia',ddi='48',coins='zł',coins_name='PLN' where id =174;
update country set country ='api.model.country.portorico',ddi='1',coins='$',coins_name='USD' where id =175;
update country set country ='api.model.country.portugal',ddi='351',coins='€',coins_name='EUR' where id =176;
update country set country ='api.model.country.quenia',ddi='254',coins='Sh',coins_name='KES' where id =177;
update country set country ='api.model.country.quirguistao',ddi='996',coins='лв',coins_name='KGS' where id =178;
update country set country ='api.model.country.quiribati',ddi='686',coins='$',coins_name='CAD' where id =179;
update country set country ='api.model.country.reinounido',ddi='44',coins='£',coins_name='GBP' where id =180;
update country set country ='api.model.country.republicacentro-africana',ddi='236',coins='$',coins_name='USD' where id =181;
update country set country ='api.model.country.republicadominicana',ddi='1',coins='$',coins_name='RD$' where id =182;
update country set country ='api.model.country.reuniao',ddi='262',coins='$',coins_name='USD' where id =183;
update country set country ='api.model.country.romenia',ddi='40',coins='lei',coins_name='RON' where id =184;
update country set country ='api.model.country.ruanda',ddi='250',coins='Fr',coins_name='RWF' where id =185;
update country set country ='api.model.country.russia',ddi='7',coins='₽',coins_name='RUB' where id =186;
update country set country ='api.model.country.saaraocidental',ddi='212',coins='$',coins_name='USD' where id =187;
update country set country ='api.model.country.samoa',ddi='685',coins='$',coins_name='SBD' where id =188;
update country set country ='api.model.country.samoaamericana',ddi='1',coins='$',coins_name='SBD' where id =189;
update country set country ='api.model.country.santahelena',ddi='290',coins='£',coins_name='SHP' where id =190;
update country set country ='api.model.country.saomarinho',ddi='378',coins='€',coins_name='EUR' where id =191;
update country set country ='api.model.country.saopedroemiquelao',ddi='508',coins='€',coins_name='EUR' where id =192;
update country set country ='api.model.country.saotomeeprincipe',ddi='239',coins='Db',coins_name='STD' where id =193;
update country set country ='api.model.country.saovicenteegranadinas',ddi='1',coins='$',coins_name='XCD' where id =194;
update country set country ='api.model.country.seicheles',ddi='248',coins='₨',coins_name='SCR' where id =195;
update country set country ='api.model.country.senegal',ddi='221',coins='Fr',coins_name='XOF' where id =196;
update country set country ='api.model.country.serilanca',ddi='94',coins='Rs',coins_name='LKR' where id =197;
update country set country ='api.model.country.serraleoa',ddi='232',coins='Le',coins_name='SLL' where id =198;
update country set country ='api.model.country.servia',ddi='381',coins='din',coins_name='RSD' where id =199;
update country set country ='api.model.country.singapura',ddi='65',coins='$',coins_name='SGD' where id =200;
update country set country ='api.model.country.siria',ddi='963',coins='£',coins_name='SYP' where id =201;
update country set country ='api.model.country.somalia',ddi='252',coins='Sh',coins_name='SOS' where id =202;
update country set country ='api.model.country.sudao',ddi='249',coins='£',coins_name='SDG' where id =203;
update country set country ='api.model.country.sudaodosul',ddi='211',coins='£',coins_name='SSP' where id =204;
update country set country ='api.model.country.suecia',ddi='46',coins='kr',coins_name='SEK' where id =205;
update country set country ='api.model.country.suica',ddi='41',coins='Fr',coins_name='CHF' where id =206;
update country set country ='api.model.country.suriname',ddi='597',coins='$',coins_name='SRD' where id =207;
update country set country ='api.model.country.tajiquistao',ddi='66',coins='฿',coins_name='THB' where id =209;
update country set country ='api.model.country.tailandia',ddi='886',coins='$',coins_name='TWD' where id =210;
update country set country ='api.model.country.taiwan',ddi='992',coins='ЅМ',coins_name='TJS' where id =208;
update country set country ='api.model.country.tanzania',ddi='255',coins='Sh',coins_name='TZS' where id =211;
update country set country ='api.model.country.tchequia',ddi='420',coins='$',coins_name='USD' where id =212;
update country set country ='api.model.country.timor-leste',ddi='670',coins='$',coins_name='USD' where id =213;
update country set country ='api.model.country.togo',ddi='228',coins='Fr',coins_name='XOF' where id =214;
update country set country ='api.model.country.toquelau',ddi='676',coins='T$',coins_name='TOP' where id =216;
update country set country ='api.model.country.tonga',ddi='690',coins='$',coins_name='USD' where id =215;
update country set country ='api.model.country.trindadeetobago',ddi='1',coins='$',coins_name='TTD' where id =217;
update country set country ='api.model.country.tunisia',ddi='216',coins='د.ت',coins_name='TND' where id =218;
update country set country ='api.model.country.turcasecaicos',ddi='1',coins='$',coins_name='USD' where id =219;
update country set country ='api.model.country.turcomenistao',ddi='993',coins='m',coins_name='TMT' where id =220;
update country set country ='api.model.country.turquia',ddi='90',coins='$',coins_name='TRY' where id =221;
update country set country ='api.model.country.tuvalu',ddi='688',coins='$',coins_name='AUD' where id =222;
update country set country ='api.model.country.ucrania',ddi='380',coins='₴',coins_name='UAH' where id =223;
update country set country ='api.model.country.uganda',ddi='256',coins='Sh',coins_name='UGX' where id =224;
update country set country ='api.model.country.uruguai',ddi='598',coins='$',coins_name='UYU' where id =225;
update country set country ='api.model.country.uzbequistao',ddi='998',coins='лв',coins_name='UZS' where id =226;
update country set country ='api.model.country.vanuatu',ddi='678',coins='Vt',coins_name='VUV' where id =227;
update country set country ='api.model.country.vaticano',ddi='379',coins='€',coins_name='EUR' where id =228;
update country set country ='api.model.country.venezuela',ddi='58',coins='Bs F',coins_name='VEF' where id =229;
update country set country ='api.model.country.vietna',ddi='84',coins='₫',coins_name='VND' where id =230;
update country set country ='api.model.country.wallisefutuna',ddi='681',coins='Fr',coins_name='XPF' where id =231;
update country set country ='api.model.country.zambia',ddi='260',coins='ZK',coins_name='ZMK' where id =232;
update country set country ='api.model.country.zimbabue',ddi='263',coins='$',coins_name='USD' where id =233;


UPDATE payment_type set name ='api.model.payment.cash' where id =1;
UPDATE payment_type set name ='api.model.payment.pix' where id =2;
UPDATE payment_type set name ='api.model.payment.mastercarddebitcard' where id =5;
UPDATE payment_type set name ='api.model.payment.mastercardcreditcard' where id =6;
UPDATE payment_type set name ='api.model.payment.elodebitcard' where id =7;
UPDATE payment_type set name ='api.model.payment.elo credit card' where id =8;
UPDATE payment_type set name ='api.model.payment.hipercardcreditcard' where id =9;
UPDATE payment_type set name ='api.model.payment.dinersclubcreditcard' where id =10;
UPDATE payment_type set name ='api.model.payment.americanexpresscreditcard' where id =11;
UPDATE payment_type set name ='api.model.payment.allelemeal' where id =12;
UPDATE payment_type set name ='api.model.payment.other' where id =13;
UPDATE payment_type set name ='api.model.payment.visadebitcard' where id =3;
UPDATE payment_type set name ='api.model.payment.visacreditcard' where id =4;


UPDATE category SET name = 'api.ido.category.gym', cod_name = 'gym' where id = 1;
UPDATE category SET name = 'api.ido.category.agro', cod_name = 'agro' where id = 2;
UPDATE category SET name = 'api.ido.category.lawyer', cod_name = 'lawyer' where id = 3;
UPDATE category SET name = 'api.ido.category.food', cod_name = 'food' where id = 4;
UPDATE category SET name = 'api.ido.category.animals', cod_name = 'animals' where id = 5;
UPDATE category SET name = 'api.ido.category.babies ', cod_name = 'babies ' where id = 6;
UPDATE category SET name = 'api.ido.category.beauty', cod_name = 'beauty' where id = 7;
UPDATE category SET name = 'api.ido.category.beverages ', cod_name = 'beverages ' where id = 8;
UPDATE category SET name = 'api.ido.category.toys', cod_name = 'toys' where id = 9;
UPDATE category SET name = 'api.ido.category.home', cod_name = 'home' where id = 10;
UPDATE category SET name = 'api.ido.category.phones', cod_name = 'phones' where id = 11;
UPDATE category SET name = 'api.ido.category.consult', cod_name = 'consult' where id = 12;
UPDATE category SET name = 'api.ido.category.construction', cod_name = 'construction' where id = 13;
UPDATE category SET name = 'api.ido.category.accounting', cod_name = 'accounting' where id = 14;
UPDATE category SET name = 'api.ido.category.dance', cod_name = 'dance' where id = 15;
UPDATE category SET name = 'api.ido.category.education', cod_name = 'education' where id = 16;
UPDATE category SET name = 'api.ido.category.appliance', cod_name = 'appliance' where id = 17;
UPDATE category SET name = 'api.ido.category.eletronic ', cod_name = 'eletronic ' where id = 18;
UPDATE category SET name = 'api.ido.category.sport', cod_name = 'sport' where id = 19;
UPDATE category SET name = 'api.ido.category.event ', cod_name = 'event ' where id = 20;
UPDATE category SET name = 'api.ido.category.graphics', cod_name = 'graphics' where id = 22;
UPDATE category SET name = 'api.ido.category.hobbies', cod_name = 'hobbies' where id = 23;
UPDATE category SET name = 'api.ido.category.informatic', cod_name = 'informatic' where id = 24;
UPDATE category SET name = 'api.ido.category.tickets', cod_name = 'tickets' where id = 25;
UPDATE category SET name = 'api.ido.category.instrument', cod_name = 'instrument' where id = 26;
UPDATE category SET name = 'api.ido.category.internet', cod_name = 'internet' where id = 27;
UPDATE category SET name = 'api.ido.category.games', cod_name = 'games' where id = 28;
UPDATE category SET name = 'api.ido.category.marketing', cod_name = 'marketing' where id = 29;
UPDATE category SET name = 'api.ido.category.fashion', cod_name = 'fashion' where id = 30;
UPDATE category SET name = 'api.ido.category.music', cod_name = 'music' where id = 31;
UPDATE category SET name = 'api.ido.category.dentistry', cod_name = 'dentistry' where id = 32;
UPDATE category SET name = 'api.ido.category.health', cod_name = 'health' where id = 33;
UPDATE category SET name = 'api.ido.category.support', cod_name = 'support' where id = 34;
UPDATE category SET name = 'api.ido.category.vehicles', cod_name = 'vehicles' where id = 35;
UPDATE category SET name = 'api.ido.category.clothing', cod_name = 'clothing' where id = 36;
UPDATE category SET name = 'api.ido.category.telephony', cod_name = 'telephony' where id = 37;
UPDATE category SET name = 'api.ido.category.transport', cod_name = 'transport' where id = 38;
UPDATE category SET name = 'api.ido.category.turism', cod_name = 'turism' where id = 39;


UPDATE activity SET segment = 'api.ido.activities.foodanddrinks' where id = 1;
UPDATE activity SET segment = 'api.ido.activities.agro' where id = 2;
UPDATE activity SET segment = 'api.ido.activities.animals' where id = 3;
UPDATE activity SET segment = 'api.ido.activities.babies' where id = 4;
UPDATE activity SET segment = 'api.ido.activities.beautyandpersonalcare' where id = 5;
UPDATE activity SET segment = 'api.ido.activities.bed;tableandbath' where id = 6;
UPDATE activity SET segment = 'api.ido.activities.toysandhobbies' where id = 7;
UPDATE activity SET segment = 'api.ido.activities.houseandgarden' where id = 8;
UPDATE activity SET segment = 'api.ido.activities.cellphonesandtelephone' where id = 9;
UPDATE activity SET segment = 'api.ido.activities.construction' where id = 10;
UPDATE activity SET segment = 'api.ido.activities.deliveryandfood' where id = 11;
UPDATE activity SET segment = 'api.ido.activities.homeappliances' where id = 12;
UPDATE activity SET segment = 'api.ido.activities.electronics' where id = 13;
UPDATE activity SET segment = 'api.ido.activities.games' where id = 14;
UPDATE activity SET segment = 'api.ido.activities.computing' where id = 15;
UPDATE activity SET segment = 'api.ido.activities.appetizer' where id = 16;
UPDATE activity SET segment = 'api.ido.activities.musicalinstruments' where id = 17;
UPDATE activity SET segment = 'api.ido.activities.market' where id = 18;
UPDATE activity SET segment = 'api.ido.activities.fashionandclothing' where id = 19;
UPDATE activity SET segment = 'api.ido.activities.health' where id = 20;
UPDATE activity SET segment = 'api.ido.activities.gymandsports' where id = 21;
UPDATE activity SET segment = 'api.ido.activities.lawyers' where id = 22;
UPDATE activity SET segment = 'api.ido.activities.animals' where id = 23;
UPDATE activity SET segment = 'api.ido.activities.consultancy' where id = 24;
UPDATE activity SET segment = 'api.ido.activities.accounting' where id = 25;
UPDATE activity SET segment = 'api.ido.activities.gastronomy' where id = 26;
UPDATE activity SET segment = 'api.ido.activities.graphicsandprinting' where id = 27;
UPDATE activity SET segment = 'api.ido.activities.education' where id = 28;
UPDATE activity SET segment = 'api.ido.activities.partyandevents' where id = 29;
UPDATE activity SET segment = 'api.ido.activities.marketingandinternet' where id = 30;
UPDATE activity SET segment = 'api.ido.activities.dentistry' where id = 31;
UPDATE activity SET segment = 'api.ido.activities.self-employedprofessional' where id = 32;
UPDATE activity SET segment = 'api.ido.activities.health' where id = 33;
UPDATE activity SET segment = 'api.ido.activities.supporttechnician' where id = 34;
UPDATE activity SET segment = 'api.ido.activities.travelandtourism' where id = 35;
UPDATE activity SET segment = 'api.ido.activities.vehiclesandtransport' where id = 36;
UPDATE activity SET segment = 'api.ido.activities.alcoholicbeverage' where id = 37;
UPDATE activity SET segment = 'api.ido.activities.others' where id = 38;
UPDATE activity SET segment = 'api.ido.activities.others' where id = 39;